# Generated by Django 3.0.8 on 2021-08-27 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20210826_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=[0], related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
